### ISSUE TITLE
Inconsistent loading and Jellyfin unable to parse tuner

### ISSUE THREAD

**Issue by geebru** [tonywagner/mlbserver#32]
## Overview

On my first install a week or two ago this worked amazingly. Quick connections, no stream drops (like my other service doing this), and I moved forward to use mlbserver in full.

Since then I've had issues getting streams to load via Embed (when just watching locally) and then via Stream through Jellyfin. I do see 1 repeated error in the logs and wanted to log the issue to a) determine if the error is the problem here or b) if there's another problem in my setup.

## Issue

The error being repeated constantly in my logs with the service running is:
`5/15/2024, 1:40:26 PM error : invalid response from url https://www.mlb.com/live-stream-games/help-center/subscription-access-big-inning`

I'm not trying to access Big Inning or anything, it just seems to be a constant issue that it can't access it for some reason. The Embed and Stream outcomes are just spinning loaders that never finish and Jellyfin claims: "Playback failed due to a server error." with the following log errors:

```
[13:47:14] [ERR] [117] Jellyfin.LiveTv.TunerHosts.M3UTunerHost: Error opening tuner
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Jellyfin.LiveTv.TunerHosts.M3UTunerHost.GetChannelStream(TunerHostInfo tunerHost, ChannelInfo channel, String streamId, IList`1 currentLiveStreams, CancellationToken cancellationToken)
   at Jellyfin.LiveTv.TunerHosts.BaseTunerHost.GetChannelStream(String channelId, String streamId, IList`1 currentLiveStreams, CancellationToken cancellationToken)
[13:47:14] [ERR] [117] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL POST /Items/201fc99428fc708e1024d74d27c0f5a9/PlaybackInfo.
```

I know Jellyfin isn't in your control but I've included it in case it can help determine problem points. I'm using the URLs provided for "Include blackouts" and the games correctly show up in my guide, but won't actually play the streams.

## Setup

Running on Unraid, my Docker compose is the following:

```
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 9999:9999 # MLBServer
      - 10000:10000 # MLBServer
    volumes:
      - /mnt/cache/appdata/gluetun:/gluetun
    environment:
      - TZ=America/New_York
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=${PROTON_IP}
      - VPN_ENDPOINT_PORT=${PROTON_PORT}
      - WIREGUARD_PUBLIC_KEY=${PROTON_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${PROTON_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=10.2.0.2/32
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - HTTPPROXY=off
      - SHADOWSOCKS=off
      - FIREWALL_OUTBOUND_SUBNETS=172.20.0.0/16,192.168.4.0/24
    network_mode: bridge
    security_opt:
      - no-new-privileges:true
    restart: always
      
  mlbserver:
    image: tonywagner/mlbserver:latest
    container_name: mlbserver
    environment:
      - TZ=America/New_York
      - data_directory=/mlbserver/data_directory
      - account_username=${MLB_EMAIL}
      - account_password=${MLB_PASSWORD}
      - zip_code=20017
      - fav_teams=BAL
    volumes:
      - /mnt/cache/appdata/mlbserver:/mlbserver/data_directory
    network_mode: service:gluetun
    restart: unless-stopped
```

I've included the VPN as I'm guessing that's involved here. I'm using it for location spoofing here for blackout games.

Let me know if any other information would be helpful!
