### ISSUE TITLE
Unable to override port 9999

### ISSUE THREAD

**Issue by catdroid75** [tonywagner/mlbserver#72]
First, thanks for this incredible bit of software.

Another container on my host is already using port 9999, so I'd like to change to port 9998. But using the compose below, mlbserver still loads on port 9999. 

Log output:
```

> Version 2025.04.06
> 
> 4/8/2025, 12:00:24 PM mlbserver started at http://172.27.0.2:9999

```
Compose file:
```
services:
  # 2025.02.13
  # GitHub home for this project: https://github.com/tonywagner/mlbserver
  # Docker Hub home for this project: https://hub.docker.com/r/tonywagner/mlbserver
  mlbserver:
    image: tonywagner/mlbserver:${TAG}
    container_name: mlbserver-og
    ports:
      - 9998:9998
    environment:
      - TZ=${TZ}
      - data_directory=${DATA_DIRECTORY}
      - account_username=${ACCOUNT_USERNAME}
      - account_password=${ACCOUNT_PASSWORD}
      - fav_teams=${FAV_TEAMS}
      - zip_code=${ZIP_CODE}
    volumes:
      - ${HOST_DIR}/mlbserver:${DATA_DIRECTORY}
    restart: unless-stopped
```

Any help is appreciated.
